// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4A5aBSAEpqXSZ_LRHbKcViPsxbOBPABA',
    appId: '1:421200004739:web:15393643df96475fd57db6',
    messagingSenderId: '421200004739',
    projectId: 'login-page-jpv',
    authDomain: 'login-page-jpv.firebaseapp.com',
    storageBucket: 'login-page-jpv.appspot.com',
    measurementId: 'G-1SPNW2RFHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qGW_JqOl648Q-ez6FG_SZNMIQVUa9Jc',
    appId: '1:421200004739:android:0e5290c5dee1be33d57db6',
    messagingSenderId: '421200004739',
    projectId: 'login-page-jpv',
    storageBucket: 'login-page-jpv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxOFPB7xp3QyoVEKFqNNBQ3Wc6LNvCuYg',
    appId: '1:421200004739:ios:55dd24c9dd48db9dd57db6',
    messagingSenderId: '421200004739',
    projectId: 'login-page-jpv',
    storageBucket: 'login-page-jpv.appspot.com',
    iosClientId: '421200004739-nmua3kjhjdah56dj70ed3dk7tpsqqblb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxOFPB7xp3QyoVEKFqNNBQ3Wc6LNvCuYg',
    appId: '1:421200004739:ios:55dd24c9dd48db9dd57db6',
    messagingSenderId: '421200004739',
    projectId: 'login-page-jpv',
    storageBucket: 'login-page-jpv.appspot.com',
    iosClientId: '421200004739-nmua3kjhjdah56dj70ed3dk7tpsqqblb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );
}
